os:
  - windows
  - linux
  - osx

addons:
  apt:
    packages:
    - autopoint

language: c

env:
  - BRANCH=0.20.2
  - BRANCH=1.0.6
  - BRANCH=1.2.4
  - BRANCH=devel

cache:
  directories:
    - "$HOME/.choosenim"

install:
  - export PATH="/usr/local/opt/gettext/bin:$PATH"
  - curl https://gist.github.com/elijahr/a72a228b9617b759a1c24062d35cc23d/raw/travis.sh -LsSf -o travis.sh
  - source travis.sh

script:
  - bash ./test.sh
